version: '3.3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: src/Clients/Web/Dockerfile
    depends_on:
      - api
    ports:
      - 5003:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
  api:
    container_name: api
    build:
      context: .
      dockerfile: src/Services/LoadBalancer/Dockerfile
    depends_on:
      - identity-api
      - catalog-api
    ports:
      - 5004:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog.API/Dockerfile
    depends_on:
      - db
      - identity-api
      - redis
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgresql=User Id=postgres;Password=postgres;Server=db;Port=5432;Database=CatalogDb;IntegratedSecurity=true;Pooling=true;
      - ConnectionStrings__Redis=redis:6379
      - CatalogOptions__PicBaseUrl=http://localhost:5004/c/books/[0]/image/
  identity-api:
    container_name: identity-api
    build:
      context: .
      dockerfile: src/Services/Identity.API/Dockerfile
    depends_on:
      - db
    ports:
      - 5002:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgresql=User Id=postgres;Password=postgres;Server=db;Port=5432;Database=IdentityDb;IntegratedSecurity=true;Pooling=true;
  redis:
      image: "redis"
      container_name: "redis-container"
      ports:
        - 6379:6379
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433
    restart: always
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
