version: '3.3'

services:
  catalog-api:
    container_name: catalog-api
    build:
      context: .
      dockerfile: src/Services/Catalog.API/Dockerfile
    depends_on:
      - catalog-db
    ports:
      - 5001:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__Postgresql=User Id=postgres;Password=postgres;Server=postgres_db;Port=5432;Database=Sms;IntegratedSecurity=true;Pooling=true;

  catalog-db:
    image: postgres
    container_name: catalog-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5433:5433
    restart: always
    volumes:
      - postgresdata-catalog:/var/lib/postgresql/data

volumes:
  postgresdata-catalog:
