apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-balancer
spec:
  selector:
    matchLabels:
      app: load-balancer
  template:
    metadata:
      labels:
        app: load-balancer
    spec:
      containers:
      - name: load-balancer
        image: djoufson/booky-load-balancer:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: load-balancer-config
              key: dev-environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: load-balancer-config
              key: urls
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: load-balancer
  ports:
  - port: 5004
    targetPort: 80
    nodePort: 30002
