apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-api
spec:
  selector:
    matchLabels:
      app: catalog-api
  template:
    metadata:
      labels:
        app: catalog-api
    spec:
      containers:
      - name: catalog-api
        image: djoufson/booky-catalog-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: catalog-config
              key: dev-environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: catalog-config
              key: urls
        - name: ConnectionStrings__Postgresql
          valueFrom:
            configMapKeyRef:
              name: catalog-config
              key: postgres-conn-string
        - name: ConnectionStrings__Redis
          valueFrom:
            configMapKeyRef:
              name: redis-config
              key: redis-url
        - name: CatalogOptions__PicBaseUrl
          valueFrom:
            configMapKeyRef:
              name: catalog-config
              key: picture-url
        - name: Postgresql__UserId
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: postgres-user
        - name: Postgresql__UserPassword
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: postgres-password
        - name: Postgresql__Server
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-url
        - name: Postgresql__Port
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-api
spec:
  type: ClusterIP
  selector:
    app: catalog-api
  ports:
  - port: 5001
    targetPort: 80
