apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: djoufson/booky-identity-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: dev-environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: urls
        - name: ConnectionStrings.Postgresql
          valueFrom:
            configMapKeyRef:
              name: identity-config
              key: postgres-conn-string
        - name: Postgresql.UserId
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: postgres-user
        - name: Postgresql.UserPassword
          valueFrom:
            secretKeyRef:
              name: postgres-config
              key: postgres-password
        - name: Postgresql.Server
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: db-url
        - name: Postgresql.Port
          value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
  - port: 5002
    targetPort: 80
