apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
      - name: identity-service
        image: djoufson/booky-identity-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: identity-config
              value: dev-environment
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              key: identity-config
              value: urls
        - name: ConnectionStrings__Postgresql
          valueFrom:
            configMapKeyRef:
              key: identity-config
              value: postgres-conn-string
        - name: Postgresql__UserId
          valueFrom:
            secretKeyRef:
              key: postgres-config
              value: postgres-user
        - name: Postgresql__UserPassword
          valueFrom:
            secretKeyRef:
              key: postgres-config
              value: postgres-password
        - name: Postgresql__Server
          valueFrom:
            configMapKeyRef:
              key: postgres-config
              value: db-url
        - name: Postgresql__Port
          value: "5433"
---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
  - port: 5002
    targetPort: 80
