name: Docker Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        run: docker-compose -f docker-compose.build.yml config --services | xargs -I {} docker-compose -f docker-compose.build.yml build {}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag and Push Docker images
        run: |
          DOCKER_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME_PREFIX=$DOCKER_USERNAME/booky

          # Loop through the services in docker-compose.build.yml
          for service in $(docker-compose -f docker-compose.build.yml config --services); do
            docker tag booky_$service:latest $IMAGE_NAME_PREFIX-$service:latest
            docker push $IMAGE_NAME_PREFIX-$service:latest
            echo "Docker image pushed to DockerHub: $IMAGE_NAME_PREFIX-$service:latest"
          done
